### ISSUE TITLE
Duplicated lines in output

### ISSUE THREAD

**Issue by ktroule** [griffithlab/pVACtools#111]
Hi, once more.
I've few question related to the output of pVACseq. Sorry if these question are already solved (I've not found them).

1º As far as I know the VEP DownstreamProtein plugin only annotates predictions for transcripts suffering of frameshfit mutations. How do you calculate the the protein change when a SNV is happening? I would be interested in having the whole protein prediction, not only when a frameshift happens but also when there is a SNV. I guess you must be doing this in pVACseq as the output contains the MT Epitope Seq which is needed for the affinity prediction.

2º See image. I've highlighted transcripts (same color, same transcripts) .
Why are there repeated lines (2 and 8, 3 and 9, 4 and 10, and so on), the rest of column sshare same parameters between those lines (scores, etc). If I run several times the same pVACseq script, Does the program overwrites the final tsv or it just adds new lines? If it appends new runs of pvacseq that might be the answer.
![pvac_out](https://user-images.githubusercontent.com/9655951/38679740-c6a92894-3e64-11e8-9548-f2f6b316fbe5.png)

Once more, thanks for your patience and help-

**Comment by ktroule** [comment]
Thanks! You can close the thread.

**Comment by ktroule** [comment]
I've been trying to use  `pvacseq generate_protein_fasta`, it runs ok with my own VCF files, but I've also tried to run it using a Cosmic vcf file. I've annotated this Cosmic vcf using the exactly same VEP parameters I use for my own vcf. But I get this error:
```
Converting VCF to TSV
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.5/site-packages/tools/pvacseq/generate_protein_fasta.py", line 111, in main
    convert_vcf(args.input_file, temp_dir)
  File "/usr/local/lib/python3.5/site-packages/tools/pvacseq/generate_protein_fasta.py", line 52, in convert_vcf
    converter.execute()
  File "/usr/local/lib/python3.5/site-packages/lib/input_file_converter.py", line 202, in execute
    genotype = entry.genotype(vcf_reader.samples[0])
IndexError: list index out of range
```

Does this program take any argument from the header that I might be missing from the Cosmic vcf file?

**Comment by susannasiebert** [comment]
Does this file have any samples in it? This code is looking for the genotype of the first sample to confirm that the variant is actually called. It's failing because there don't appear to be any sample columns in the VCF.

**Comment by ktroule** [comment]
No, it just contains a header such this: #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO 

I'll add a sample columns to make it work.

Thanks I appreciate it.

**Comment by ktroule** [comment]
I get this error: `ERROR: There was a mismatch between the actual wildtype amino acid and the expected amino acid. Did you use the same reference build version for VEP that you used for creating the VCF?`
The VCF and the VEP annotation both come from the same genome.

**Comment by susannasiebert** [comment]
Ok, so they were the same build? Because usually this error means that the the variant calling was done with build 37 while VEP annotation happened with build 38, or vice versa. Without seeing the VCF entry that caused this issue, I won't be able to further investigate.

**Comment by ktroule** [comment]
Both are build 37
Original VCF
```
##source=COSMICv84
##reference=GRCh37
```
Once VCF is annotated with VEP
`##VEP="v90" time="2018-04-13 08:57:06" cache="/local/Referencias/VEP/VEP90/.vep/homo_sapiens/90_GRCh37" ensembl-variation=90.8684f2b ensembl-funcgen=90.e775c00 ensembl-io=90.9a148ea ensembl=90.4a44397 1000genomes="phase3" COSMIC="81" ClinVar="201706" ESP="20141103" HGMD-PUBLIC="20164" assembly="GRCh37.p13" dbSNP="150" gencode="GENCODE 19" genebuild="2011-04" gnomAD="170228" polyphen="2.2.2" regbuild="1.0" sift="sift5.2.2`

**Comment by susannasiebert** [comment]
Are you able to share the VCF that is causing this issue? If you don't want to share on here you can also email it to us at help@pvactools.org.

**Comment by ktroule** [comment]
Sure, no problem It's from Cosmic, 

You can download it from here (its too heavy ~320mb): https://cancer.sanger.ac.uk/cosmic/download the one I'm using is: VCF file of all non coding mutations in the current release.

There is no need to process the whole file, the error happens in the first chromosome, for instance these three genes/transcripts produce errors: ENST00000270722, TCEA3, CDKN2C.

If more info is needed let me know it.

Thanks.

**Comment by susannasiebert** [comment]
The problem is with the VEP annotation so if you could attach the annotated version you have, that would be very helpful.

**Comment by ktroule** [comment]
Just selected the top variants of the file and annotate it. It contains at leas one line that makes the code fail.
```
ERROR: There was a mismatch between the actual wildtype amino acid and the expected amino acid. Did you use the same reference build version for VEP that you used for creating the VCF?
{'stop': '3350375', 'protein_position': '1276-1277', 'variant': 'C', 'chromosome_name': '1', 'reference': 'CCTCTGA', 'wildtype_amino_acid_sequence': 'MRSKARARKLAKSDGDVVNNMYEPNRDLLASHSAEDEAEDSAMSPIPVGPPSPFPTSEDFTPKEGSPYEAPVYIPEDIPIPADFELRESSIPGAGLGVWAKRKMEAGERLGPCVVVPRAAAKETDFGWEQILTDVEVSPQEGCITKISEDLGSEKFCVDANQAGAGSWLKYIRVACSCDDQNLTMCQISEQIYYKVIKDIEPGEELLVHVKEGVYPLGTVPPGLDEEPTFRCDECDELFQSKLDLRRHKKYTCGSVGAALYEGLAEELKPEGLGGGSGQAHECKDCERMFPNKYSLEQHMVIHTEEREYKCDQCPKAFNWKSNLIRHQMSHDSGKRFECENCVKVFTDPSNLQRHIRSQHVGARAHACPDCGKTFATSSGLKQHKHIHSTVKPFICEVCHKSYTQFSNLCRHKRMHADCRTQIKCKDCGQMFSTTSSLNKHRRFCEGKNHYTPGGIFAPGLPLTPSPMMDKAKPSPSLNHASLGFNEYFPSRPHPGSLPFSTAPPTFPALTPGFPGIFPPSLYPRPPLLPPTSLLKSPLNHTQDAKLPSPLGNPALPLVSAVSNSSQGTTAAAGPEEKFESRLEDSCVEKLKTRSSDMSDGSDFEDVNTTTGTDLDTTTGTGSDLDSDVDSDPDKDKGKGKSAEGQPKFGGGLAPPGAPNSVAEVPVFYSQHSFFPPPDEQLLTATGAAGDSIKAIASIAEKYFGPGFMGMQEKKLGSLPYHSAFPFQFLPNFPHSLYPFTDRALAHNLLVKAEPKSPRDALKVGGPSAECPFDLTTKPKDVKPILPMPKGPSAPASGEEQPLDLSIGSRARASQNGGGREPRKNHVYGERKLGAGEGLPQVCPARMPQQPPLHYAKPSPFFMDPIYSRVEKRKVTDPVGALKEKYLRPSPLLFHPQMSAIETMTEKLESFAAMKADSGSSLQPLPHHPFNFRSPPPTLSDPILRKGKERYTCRYCGKIFPRSANLTRHLRTHTGEQPYRCKYCDRSFSISSNLQRHVRNIHNKEKPFKCHLCNRCFGQQTNLDRHLKKHEHENAPVSQHPGVLTNHLGTSASSPTSESDNHALLDEKEDSYFSEIRNFIANSEMNQASTRTEKRADMQIVDGSAQCPGLASEKQEDVEEEDDDDLEEDDEDSLAGKSQDDTVSPAPEPQAAYEDEEDEEPAASLAVGFDHTRRCAEDHEGGLLALEPMPTFGKGLDLRRAAEEAFEVKDVLNSTLDSEALKHTLCRQAKNQAYAMMLSLSEDTPLHTPSQGSLDAWLKVTGATSESGAFHPINHL', 'normal_vaf': 'NA', 'variant_type': 'inframe_del', 'protein_length_change': '', 'downstream_amino_acid_sequence': '', 'ensembl_gene_id': 'ENSG00000142611', 'normal_depth': 'NA', 'tdna_depth': 'NA', 'trna_depth': 'NA', 'transcript_name': 'ENST00000270722', 'index': 'PRDM16.ENST00000270722.inframe_del.1276-1277L*/-', 'gene_expression': 'NA', 'transcript_expression': 'NA', 'start': '3350369', 'trna_vaf': 'NA', 'tdna_vaf': 'NA', 'amino_acid_change': 'L*/-', 'gene_name': 'PRDM16', 'fusion_amino_acid_sequence': ''}

```
[VCFannotated.zip](https://github.com/griffithlab/pVACtools/files/1910748/VCFannotated.zip)

**Comment by susannasiebert** [comment]
What version of pVACtools are you running? This seems to be caused by a bug related to mutations that involve a stop codon (either stop gained or stop lost), which was fixed in version 1.0.3. I ran your VCF with the newest version and it finished successfully.

**Comment by ktroule** [comment]
Indeed, it's the 1.02 version.

Thanks!

**Comment by ktroule** [comment]
Still having problems, now with pvactools 1.0.3.
As I'm running pvacq in parallel I just can show a message of error for one of the files.

```
ERROR: There was a mismatch between the actual wildtype amino acid and the expected amino acid. Did you use the same reference build version for VEP that you used for creating the VCF?
{'index': '1058875.CTNNB1.ENST00000349496.inframe_del.3-126TQGLCH*IFSY*IGALLRCH*ASLAEIPLLSSLPAYLSGYLLLHFLLTPPNGLVK*QTSHQQESSLDDCFWSLDAVPFFH*FSE*LLGGSLRD*VFHH*ANPGYHSAFLGCLSDLTLFLKIFQWVISQILFF*IKVTFPIY*C*YCFVFIADLMELDMAMEPDRKAAVSHWQQQSYLDSGIHSGATTTAPSLSGKGNPEEEDVDTSQVLYEWEQGFSQSFTQEQVAGKSIIFHCLTESQNAVLRTKKLVYNSLNKMLW*RKESNSNVTFTI*DSKYLGKC*TVDSEC*INLFQILMDSMQ*LELRGYELLCSLRH*MRACRSHLHSLMLLIPLMSSVWX/-', 'tdna_depth': 'NA', 'chromosome_name': '3', 'normal_vaf': 'NA', 'gene_name': 'CTNNB1', 'tdna_vaf': 'NA', 'reference': 'TACTCAAGGTTTGTGTCATTAAATCTTTAGTTACTGAATTGGGGCTCTGCTTCGTTGCCATTAAGCCAGTCTGGCTGAGATCCCCCTGCTTTCCTCTCTCCCTGCTTACTTGTCAGGCTACCTTTTGCTCCATTTTCTGCTCACTCCTCCTAATGGCTTGGTGAAATAGCAAACAAGCCACCAGCAGGAATCTAGTCTGGATGACTGCTTCTGGAGCCTGGATGCAGTACCATTCTTCCACTGATTCAGTGAGTAACTGTTAGGTGGTTCCCTAAGGGATTAGGTATTTCATCACTGAGCTAACCCTGGCTATCATTCTGCTTTTCTTGGCTGTCTTTCAGATTTGACTTTATTTCTAAAAATATTTCAATGGGTCATATCACAGATTCTTTTTTTTTAAATTAAAGTAACATTTCCAATCTACTAATGCTAATACTGTTTCGTATTTATAGCTGATTTGATGGAGTTGGACATGGCCATGGAACCAGACAGAAAAGCGGCTGTTAGTCACTGGCAGCAACAGTCTTACCTGGACTCTGGAATCCATTCTGGTGCCACTACCACAGCTCCTTCTCTGAGTGGTAAAGGCAATCCTGAGGAAGAGGATGTGGATACCTCCCAAGTCCTGTATGAGTGGGAACAGGGATTTTCTCAGTCCTTCACTCAAGAACAAGTAGCTGGTAAGAGTATTATTTTTCATTGCCTTACTGAAAGTCAGAATGCAGTTTTGAGAACTAAAAAGTTAGTGTATAATAGTTTAAATAAAATGTTGTGGTGAAGAAAAGAGAGTAATAGCAATGTCACTTTTACCATTTAGGATAGCAAATACTTAGGTAAATGCTGAACTGTGGATAGTGAGTGTTGAATTAACCTTTTCCAGATATTGATGGACAGTATGCAATGACTCGAGCTCAGAGGGTACGAGCTGCTATGTTCCCTGAGACATTAGATGAGGGCATGCAGATCCCATCTACACAGTTTGATGCTGCTCATCCCACTAATGTCCAGCGTTTGGCT', 'variant': 'T', 'wildtype_amino_acid_sequence': 'MATQADLMELDMAMEPDRKAAVSHWQQQSYLDSGIHSGATTTAPSLSGKGNPEEEDVDTSQVLYEWEQGFSQSFTQEQVADIDGQYAMTRAQRVRAAMFPETLDEGMQIPSTQFDAAHPTNVQRLAEPSQMLKHAVVNLINYQDDAELATRAIPELTKLLNDEDQVVVNKAAVMVHQLSKKEASRHAIMRSPQMVSAIVRTMQNTNDVETARCTAGTLHNLSHHREGLLAIFKSGGIPALVKMLGSPVDSVLFYAITTLHNLLLHQEGAKMAVRLAGGLQKMVALLNKTNVKFLAITTDCLQILAYGNQESKLIILASGGPQALVNIMRTYTYEKLLWTTSRVLKVLSVCSSNKPAIVEAGGMQALGLHLTDPSQRLVQNCLWTLRNLSDAATKQEGMEGLLGTLVQLLGSDDINVVTCAAGILSNLTCNNYKNKMMVCQVGGIEALVRTVLRAGDREDITEPAICALRHLTSRHQEAEMAQNAVRLHYGLPVVVKLLHPPSHWPLIKATVGLIRNLALCPANHAPLREQGAIPRLVQLLVRAHQDTQRRTSMGGTQQQFVEGVRMEEIVEGCTGALHILARDVHNRIVIRGLNTIPLFVQLLYSPIENIQRVAAGVLCELAQDKEAAEAIEAEGATAPLTELLHSRNEGVATYAAAVLFRMSEDKPQDYKKRLSVELTSSLFRTEPMAWNETADLGLDIGAQGEPLGYRQDDPSYRSFHSGGYGQDALGMDPMMEHEMGGHHPGADYPVDGLPDLGHAQDLMDGLPPGDSNQLAWFDTDL', 'variant_type': 'inframe_del', 'gene_expression': 'NA', 'trna_depth': 'NA', 'fusion_amino_acid_sequence': '', 'amino_acid_change': 'TQGLCH*IFSY*IGALLRCH*ASLAEIPLLSSLPAYLSGYLLLHFLLTPPNGLVK*QTSHQQESSLDDCFWSLDAVPFFH*FSE*LLGGSLRD*VFHH*ANPGYHSAFLGCLSDLTLFLKIFQWVISQILFF*IKVTFPIY*C*YCFVFIADLMELDMAMEPDRKAAVSHWQQQSYLDSGIHSGATTTAPSLSGKGNPEEEDVDTSQVLYEWEQGFSQSFTQEQVAGKSIIFHCLTESQNAVLRTKKLVYNSLNKMLW*RKESNSNVTFTI*DSKYLGKC*TVDSEC*INLFQILMDSMQ*LELRGYELLCSLRH*MRACRSHLHSLMLLIPLMSSVWX/-', 'transcript_name': 'ENST00000349496', 'protein_length_change': '', 'normal_depth': 'NA', 'trna_vaf': 'NA', 'stop': '41266581', 'start': '41265565', 'protein_position': '3-126', 'downstream_amino_acid_sequence': '', 'ensembl_gene_id': 'ENSG00000168036', 'transcript_expression': 'NA'}
```

**Comment by susannasiebert** [comment]
Looks like another problem with stop codons since there are multiple `*` in the amino acid change. I will investigate further for a solution.

**Comment by ktroule** [comment]
Thanks, If you need more info I'm glad to help.

**Comment by ktroule** [comment]
Here you have it. I've split the original vcf file in 9, and it seems that just the first one has been processed correctly, but as I'm using GNU parallel I just can see where the latest file broke.
Attached you'll find the vcf that contains the latest error (I've just grep the lines that seems to be causing the error, the whole file is too heavy).

[VCF.zip](https://github.com/griffithlab/pVACtools/files/1921559/VCF.zip)

**Comment by ktroule** [comment]
Does the code fails at any stop codon change (stop_decat, stop_gained, stop_lost, stop_retained) or just in one of those classes?

Once more, thanks.

**Comment by ktroule** [comment]
I've been able to catch some sequence that produce errors (even when removing those lines containing the word stop) when running pvacseq (it seems to be happening because of the proteine generation scrip).

Just in case this is helpful

`{'index': '39805.ELK3.ENST00000547249.inframe_del.38-39AX/X', 'trna_vaf': 'NA', 'gene_name': 'ELK3', 'tdna_vaf': 'NA', 'tdna_depth': 'NA', 'fusion_amino_acid_sequence': '', 'trna_depth': 'NA', 'start': '96617457', 'stop': '96617460', 'variant': 'C', 'normal_vaf': 'NA', 'protein_length_change': '', 'wildtype_amino_acid_sequence': 'MESAITLWQFLLQLLLDQKHEHLICWTSNDGEFKLLKA', 'transcript_name': 'ENST00000547249', 'gene_expression': 'NA', 'variant_type': 'inframe_del', 'amino_acid_change': 'AX/X', 'reference': 'CAGA', 'chromosome_name': '12', 'normal_depth': 'NA', 'ensembl_gene_id': 'ENSG00000111145', 'protein_position': '38-39', 'transcript_expression': 'NA', 'downstream_amino_acid_sequence': ''}`

`{'normal_depth': 'NA', 'protein_length_change': '', 'protein_position': '154-156', 'downstream_amino_acid_sequence': '', 'trna_vaf': 'NA', 'index': '35957.TP53.ENST00000514944.inframe_del.154-156NRX/X', 'trna_depth': 'NA', 'tdna_depth': 'NA', 'ensembl_gene_id': 'ENSG00000141510', 'stop': '7577541', 'amino_acid_change': 'NRX/X', 'gene_expression': 'NA', 'variant': 'C', 'transcript_name': 'ENST00000514944', 'chromosome_name': '17', 'fusion_amino_acid_sequence': '', 'gene_name': 'TP53', 'normal_vaf': 'NA', 'reference': 'CTCCGGT', 'tdna_vaf': 'NA', 'wildtype_amino_acid_sequence': 'MEEPQSDPSVEPPLSQETFSDLWKLLPENNVLYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNR', 'transcript_expression': 'NA', 'start': '7577535', 'variant_type': 'inframe_del'}`

**Comment by susannasiebert** [comment]
https://github.com/griffithlab/pVACtools/pull/114 has been merged and a new version is now live (1.0.4). Please update to the latest version and let me know if you run into anymore errors.

**Comment by ktroule** [comment]
Sure. I'll run and check it.

**Comment by ktroule** [comment]
I've run about 10% of the samples and so far no errors. 
If anything appears I'll let you kow.

thanks

**Comment by ktroule** [comment]
I've a doubt for which I've no answer.
The first step, when the vcf file is converted to tsv it looks to me that some information (variants) are lost. The tsv file contains less lines the vcf. Those variants that contain no info in the field of wildtypeprotein won't appear in the the tsv files. But I still do not find the logical for some other variants that do not appear at the tsv files.


Once more thanks for your time.

**Comment by chrisamiller** [comment]
Please paste an example of a VCF line that is not carried forward

**Comment by ktroule** [comment]
For instance, I'm not being able to find this variant in any of the the TSV files.

`1       31188934        COSM4519813     C       T       .       .       GENE=MATN1;STRAND=-;CDS=c.1029G>A;AA=p.R343R;CNT=1;AC=1;AF=0.500;AN=2;BaseQRankSum=2.73;DB;DP=96;FS=2.118;MQ=60.00;MQ0=0;MQRankSum=-1.371e+00;QD=7.37;ReadPosRankSum=1.41;SOR=0.976;cross=tumor;;CSQ=T|synonymous_variant|LOW|MATN1|ENSG00000162510|Transcript|ENST00000373765|protein_coding|5/8||||1065|1029|343|R|cgG/cgA|||-1||SNV|HGNC|6907|MRVLSGTSLMLCSLLLLLQALCSPGLAPQSRGHLCRTRPTDLVFVVDSSRSVRPVEFEKVKVFLSQVIESLDVGPNATRVGMVNYASTVKQEFSLRAHVSKAALLQAVRRIQPLSTGTMTGLAIQFAITKAFGDAEGGRSRSPDISKVVIVVTDGRPQDSVQDVSARARASGVELFAIGVGSVDKATLRQIASEPQDEHVDYVESYSVIEKLSRKFQEAFCVVSDLCATGDHDCEQVCISSPGSYTCACHEGFTLNSDGKTCNVCSGGGGSSATDLVFLIDGSKSVRPENFELVKKFISQIVDTLDVSDKLAQVGLVQYSSSVRQEFPLGRFHTKKDIKAAVRNMSYMEKGTMTGAALKYLIDNSFTVSSGARPGAQKVGIVFTDGRSQDYINDAAKKAKDLGFKMFAVGVGNAVEDELREIASEPVAEHYFYTADFKTINQIGKKLQKKICVEEDPCACESLVKFQAKVEGLLQALTRKLEAVSKRLAILENTVV||     GT:AD:DP:GQ:PL  0/1:66,30:96:99:736,0,1610`

**Comment by ktroule** [comment]
Neither this one

`1       31188946        COSM3689594     C       T       .       .       GENE=MATN1;STRAND=-;CDS=c.1017G>A;AA=p.K339K;CNT=1;AC=1;AF=0.500;AN=2;BaseQRankSum=2.73;DB;DP=96;FS=2.118;MQ=60.00;MQ0=0;MQRankSum=-1.371e+00;QD=7.37;ReadPosRankSum=1.41;SOR=0.976;cross=tumor;;CSQ=T|synonymous_variant|LOW|MATN1|ENSG00000162510|Transcript|ENST00000373765|protein_coding|5/8||||1053|1017|339|K|aaG/aaA|||-1||SNV|HGNC|6907|MRVLSGTSLMLCSLLLLLQALCSPGLAPQSRGHLCRTRPTDLVFVVDSSRSVRPVEFEKVKVFLSQVIESLDVGPNATRVGMVNYASTVKQEFSLRAHVSKAALLQAVRRIQPLSTGTMTGLAIQFAITKAFGDAEGGRSRSPDISKVVIVVTDGRPQDSVQDVSARARASGVELFAIGVGSVDKATLRQIASEPQDEHVDYVESYSVIEKLSRKFQEAFCVVSDLCATGDHDCEQVCISSPGSYTCACHEGFTLNSDGKTCNVCSGGGGSSATDLVFLIDGSKSVRPENFELVKKFISQIVDTLDVSDKLAQVGLVQYSSSVRQEFPLGRFHTKKDIKAAVRNMSYMEKGTMTGAALKYLIDNSFTVSSGARPGAQKVGIVFTDGRSQDYINDAAKKAKDLGFKMFAVGVGNAVEDELREIASEPVAEHYFYTADFKTINQIGKKLQKKICVEEDPCACESLVKFQAKVEGLLQALTRKLEAVSKRLAILENTVV||     GT:AD:DP:GQ:PL  0/1:66,30:96:99:736,0,1610`

Or this

`1       46662402        COSM6127069     C       T       .       .       GENE=POMGNT1_ENST00000535522;STRAND=-;CDS=c.288+1G>A;AA=p.?;CNT=1;AC=1;AF=0.500;AN=2;BaseQRankSum=2.73;DB;DP=96;FS=2.118;MQ=60.00;MQ0=0;MQRankSum=-1.371e+00;QD=7.37;ReadPosRankSum=1.41;SOR=0.976;cross=tumor;;CSQ=T|splice_donor_variant|HIGH|POMGNT1|ENSG00000085998|Transcript|ENST00000371992|protein_coding||4/22||||||||||-1||SNV|HGNC|19139|MDDWKPSPLIKPFGARKKRSWYLTWKYKLTNQRALRRFCQTGAVLFLLVTVIVNIKLILDTRRAISEANEDPEPEQDYDEALGRLEPPRRRGSGPRRVLDVEVYSSRSKVYVAVDGTTVLEDEAREQGRGIHVIVLNQATGHVMAKRVFDTYSPHEDEAMVLFLNMVAPGRVLICTVKDEGSFHLKDTAKALLRSLGSQAGPALGWRDTWAFVGRKGGPVFGEKHSKSPALSSWGDPVLLKTDVPLSSAEEAECHWADTELNRRRRRFCSKVEGYGSVCSCKDPTPIEFSPDPLPDNKVLNVPVAVIAGNRPNYLYRMLRSLLSAQGVSPQMITVFIDGYYEEPMDVVALFGLRGIQHTPISIKNARVSQHYKASLTATFNLFPEAKFAVVLEEDLDIAVDFFSFLSQSIHLLEEDDSLYCISAWNDQGYEHTAEDPALLYRVETMPGLGWVLRRSLYKEELEPKWPTPEKLWDWDMWMRMPEQRRGRECIIPDVSRSYHFGIVGLNMNGYFHEAYFKKHKFNTVPGVQLRNVDSLKKEAYEVEVHRLLSEAEVLDHSKNPCEDSFLPDTEGHTYVAFIRMEKDDDFTTWTQLAKCLHIWDLDVRGNHRGLWRLFRKKNHFLMSEEATLSHPNFPGATPKGGGSPRSPRTDMRPPPGPCGAGPGSESNLFIDCPEGLENRPNLEGLDFFLGWNAALRVGLALTQETAVPNPWTGPAGAHMLTQTHSETLRHWTRPPLSLLFVQISKAG||      GT:AD:DP:GQ:PL  0/1:66,30:96:99:736,0,1610`

**Comment by susannasiebert** [comment]
Hi Kyle,

These variants don't have a consequence that is supported by pVACseq. pVACseq only process variants that were annotated by VEP as `missense_variant`, `inframe_insertion`, `inframe_deletion`, or `frameshift_variant`. You examples are of a `synonymous_variant` and a `splice_donor_variant`. These types or variants are skipped when creating the TSV since they are not supported.

Thanks,
Susanna

**Comment by ktroule** [comment]
Oh, I knew that., but didn't notice that all the examples were for synonymous.

Thanks
Kevin
