### ISSUE TITLE
pvacseq stopped to become zombie process

### ISSUE THREAD

**Issue by oldteng** [griffithlab/pVACtools#333]
* pvactools version: 1.3.3
* Python version: 3.5.6
* Operating System: CentOS 6

**Describe the bug**
I use the Protable Batch System(PBS) to run the script on our computer clusters and the runtime of this work never changed after running for couple of hours. Besides, there are also no new files written in the /tmp dir and any new logs.
I can't find any error logs in my log file. It just didn't refresh any new logs.
When I use 'top' command, it seems that there are many zombie processes.
As you see, I changed the -d and -s threshold but I didn't solve the problem. I also tried to kill the script and ran it again.

My two sample vcf and a log file is shared through google drive
https://drive.google.com/drive/folders/1FH9NYtOFnpZEkW25VM7FrX2gpdY2QmJI?usp=sharing

**To Reproduce**
```
pvacseq run ${WORKDIR}/09_pVACOut/${sample}/${sample}.exp.vcf \
TUMOR \
HLA-A*02:07,HLA-A*11:01,HLA-B*39:01,HLA-B*51:01,HLA-C*07:02,HLA-C*14:02,DRB1*12:02,DRB1*15:01,DQB1*06:02,DQB1*03:01 \
MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \
${WORKDIR}/09_pVACOut/${sample}/pvac_out_test \
-e 8,9,10 \
-t 24 \
--normal-sample-name NORMAL \
--iedb-install-directory /home/work01/software/MHC/ \
-d 500 -s 100
```

**Comment by susannasiebert** [comment]
We are aware of this issue and it's being tracked in GitHub issue $327. We haven't been able to isolate the root cause but we're testing out a few things on our end.

Are you using Docker by any chance? I have a code change that I would be happy to have you try out  before the next release. It's still being tested so I'm not 100% confident that it will solve the problem but it would be great if you could give it a try and see if it fixes the problem for you.

**Comment by oldteng** [comment]
I'm afraid we don't have a docker on our computer cluster. Does it have to run on docker?

**Comment by susannasiebert** [comment]
It doesn't but that's the easiest way to share an unreleased version. I have attached a zipped version of a .whl file that you can use to install the test version like so `pip install pvactools-1.3.4a0-py3-none-any.whl`. 

[pvactools-1.3.4a0-py3-none-any.whl.zip](https://github.com/griffithlab/pVACtools/files/3003662/pvactools-1.3.4a0-py3-none-any.whl.zip)

**Comment by oldteng** [comment]
Thanks a lot! I will try it then.
By the way, is the problem only for multi threads? I wonder if I can run the command with single thread.

**Comment by susannasiebert** [comment]
Yes, it should work without using multithreading.

**Comment by oldteng** [comment]
The program shutdown with 3 errors with the same message;

> Traceback (most recent call last):
  File "/home/work01/software/anaconda3/envs/pvactest/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/home/work01/software/anaconda3/envs/pvactest/lib/python3.5/site-packages/tools/pvacseq/main.py", line 99, in main
    args[0].func.main(args[1])
  File "/home/work01/software/anaconda3/envs/pvactest/lib/python3.5/site-packages/tools/pvacseq/run.py", line 172, in main
    pipeline.execute()
  File "/home/work01/software/anaconda3/envs/pvactest/lib/python3.5/site-packages/lib/pipeline.py", line 488, in execute
    self.call_iedb(chunks)
  File "/home/work01/software/anaconda3/envs/pvactest/lib/python3.5/site-packages/lib/pipeline.py", line 398, in call_iedb
    p4.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - Entries %s - Completed" % (a, epl, method, fasta_chunk))
  File "/home/work01/software/anaconda3/envs/pvactest/lib/python3.5/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by susannasiebert** [comment]
Can you please upload the full log file?

**Comment by oldteng** [comment]
Oh, I find the problem because I did some change on file prediction_class.py because of the conda version.
I copy the change directly from the pvactools1.3.3. And you have changed the original code on line 63 to
`response = run(['/bin/bash', '-c', 'source activate pvactools_py27; python {}'.format(arguments)], stdout=response_fh, check=True)`

I changed your new code in version 1.3.4 and I will have a try. Hope the error has gone.

**Comment by susannasiebert** [comment]
There are some other changes around that line as well related to the response_fh so make sure you make those as well.

**Comment by oldteng** [comment]
I think it doesn't matter much.
Because of the conda version(My conda version is 4.6.8), the command `source activate` is no more supported. I changed it to `source /home/work01/software/anaconda3/etc/profile.d/conda.sh && conda activate pvactools_py27`, and I did the same to the file call_iedb.py

**Comment by susannasiebert** [comment]
Thanks for pointing that out. I will make an issue to update these to `conda activate`.

**Comment by oldteng** [comment]
The new version still not work well with the same problem.
Here is my log file.
Now I'm trying to run it with single thread
[BYP-pvac.zip](https://github.com/griffithlab/pVACtools/files/3006066/BYP-pvac.zip)

**Comment by susannasiebert** [comment]
Please upgrade to version 1.3.4. That version should fix the issue.

**Comment by oldteng** [comment]
I'm afraid there is still the same problem with my sample. Though I have finished with single thread, I tried with version 1.3.4 and multi threads. However, it still dies with no message.
Here is my logs. 
[BYP-pvac.zip](https://github.com/griffithlab/pVACtools/files/3036552/BYP-pvac.zip)

**Comment by tdw1221** [comment]
I'm running into the same issue on our cluster, it happens when I trying to run with -thread > 1, it goes away when using single thread, and this happens quite random, sometimes it happens sometimes it doesn't

**Comment by susannasiebert** [comment]
Thanks for keeping us in the loop with this. We're working very hard on our end to resolve this issue but multithreading is incredibly difficult to debug. Please be assured that this is our top priority right now.

@tdw1221 it would help us immensely if could you share your commands that you ran as well as the stdout from them. 

From our debugging attempts we think multithreading hangs specifically when MHCnuggetsI/II and/or MHCflurry is selected as a prediction algorithm. Can you confirm that this is the case for you as well? The stdout should have a message for each prediction call before and after making the prediction. The ones that hang have the first message but not the latter so it is possible to identify from the stdout which threads specifically are hanging. For example, you can run:
```
grep 'Making binding prediction' <stdout log file> | grep Method  | cut -f6,10,13,16 -d' ' | sort | uniq -c | sort | head
```
to identify the hung threads. The ones with `1` in the first column are hung.

If you could try to run without MHCnuggets and MHCflurry and confirm whether that hangs for you or not, that would be great. Right now we're trying to collect as many data points as possible to help narrow down where things are going wrong.

**Comment by susannasiebert** [comment]
We believe that the problem was related to MHCflurry and MHCnuggets, which both used tensorflow. Our usage of their modules and tensorflow seems to be incompatible with being run in multiprocessing mode. As a stop-gap measure, release 1.3.5 removes MHCflurry and MHCnuggets from multiprocessing. We will attempt to rework our usage so that we can use them in multiprocessing in the future. For now, please give version 1.3.5 a try and let me know if it fixes the stalling issue for you/

**Comment by susannasiebert** [comment]
We've been doing more extensive testing on our end and haven't run into any stalling using version 1.3.5. I'm resolving this issue but please do reopen if the problem persists for you.
