### ISSUE TITLE
Running reference proteome similarity

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVACtools#686]
* pvactools version: 2.0.2
* Python version: 3.7.7
* Operating System: CentOS

**Describe the bug**
After running <100 CPU hrs for BLAST similarity search, end up with this error. 
Is this something to do with peptide length? or file missing? 

**To Reproduce**
pvacseq run --iedb-install-directory /ref/dir -c 1 -t 8 -e1 8,9,10,11 --run-reference-proteome-similarity -a sample_name  "$test" "$donor" "$a1","$a2","$b1","$b2","$c1","$c2" NetMHCpan ${pVACout_Prot}/"$donor"

**Log Output**
```
Traceback (most recent call last):
  File "/software/pVACtools/pVACtools-2.0.2-venv/bin/pvacseq", line 10, in <module>
    sys.exit(main())
  File "/software/pVACtools/pVACtools-2.0.2-venv/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/software/pVACtools/pVACtools-2.0.2-venv/lib/python3.7/site-packages/tools/pvacseq/run.py", line 122, in main
    pipeline.execute()
  File "/software/pVACtools/pVACtools-2.0.2-venv/lib/python3.7/site-packages/lib/pipeline.py", line 504, in execute
    PostProcessor(**post_processing_params).execute()
  File "/software/pVACtools/pVACtools-2.0.2-venv/lib/python3.7/site-packages/lib/post_processor.py", line 37, in execute
    self.calculate_reference_proteome_similarity()
  File "/software/pVACtools/pVACtools-2.0.2-venv/lib/python3.7/site-packages/lib/post_processor.py", line 139, in calculate_reference_proteome_similarity
    file_type=self.file_type
  File "/software/pVACtools/pVACtools-2.0.2-venv/lib/python3.7/site-packages/lib/calculate_reference_proteome_similarity.py", line 129, in execute
    peptide = self.extract_n_mer_from_fs(mt_records_dict[line['Index']], wt_records_dict[line['Index']], epitope, int(line['Sub-peptide Position']))
  File "/software/pVACtools/pVACtools-2.0.2-venv/lib/python3.7/site-packages/lib/calculate_reference_proteome_similarity.py", line 96, in extract_n_mer_from_fs
    diff_position = [i for i in range(len(wt_peptide)) if wt_peptide[i] != full_peptide[i]][0]
  File "/software/pVACtools/pVACtools-2.0.2-venv/lib/python3.7/site-packages/lib/calculate_reference_proteome_similarity.py", line 96, in <listcomp>
    diff_position = [i for i in range(len(wt_peptide)) if wt_peptide[i] != full_peptide[i]][0]
IndexError: string index out of range

```

**Output File**
No final output file
.
├── log
 │   └── inputs.yml
├── Donor_ID.all_epitopes.aggregated.tsv
├── Donor_ID.all_epitopes.tsv
├── Donor_ID.fasta
├── Donor_ID.tsv
├── Donor_ID.tsv_1001-1100
├──Donor_ID.tsv_101-200
└── tmp
    ├── Donor_ID.10.fa.split_1001-1200
    ├── Donor_ID.10.fa.split_1001-1200.key

**Expected behavior**

**Comment by susannasiebert** [comment]
Thank you for this error report. I apologize that you are running into trouble with this step. This issue should be resolved in our latest version (2.0.3). Please let me know if you continue to encounter errors.

**Comment by venkataddala** [comment]
Thank you for your response. Much appreciate your help. 
I've updated to 2.0.3, still missing `.filtered.tsv.reference_matches` file. Could you please verify!

**Comment by susannasiebert** [comment]
Ok, that is strange. Even if no hits were found, I would at least expect there to be a `.filtered.tsv.reference_matches` file with just the header. Were there any other errors or log messages that might indicate what is going on here? Does the `filtered.tsv` file have a column for `Reference Match`?

**Comment by susannasiebert** [comment]
@atwollam determined that the reference matches file was being created in a tmp directory but not copied into the final output location. I made a PR (#687) to fix this issue and will make a new hotfix release later this week. I apologize for this oversight.

**Comment by venkataddala** [comment]
Just checking, is this resolved in the new release?

**Comment by susannasiebert** [comment]
Unfortunately, I have not had a chance yet to make a new release. We received quite a few bug reports that I'm in the process of resolving to be able to include them all in one release. I hopefully be able to make a new release in the next few days.

**Comment by susannasiebert** [comment]
I just made a new release (2.0.4) that should fix this problem. I'm closing this issue but please do reopen it if you're still having problems.
